### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by ghost** [luoshunchong/CCF-BDCI-Scripted-character-emotion-recognition#1]
在跑chinesebert 时出现这个问题是什么原因呀？
loading data ...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertTokenizer'. 
The class this function is called from is 'ChineseBertTokenizerFast'.
start training ...
--------------------------------- 1 fold ---------------------------------
  0%|                                                                                                                                                      | 0/3652 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "reg_chineseBERT_fgm_fold_ensemble.py", line 450, in <module>
    model_train(args, train_df, tokenizer)
  File "reg_chineseBERT_fgm_fold_ensemble.py", line 315, in model_train
    outputs = model(ids, mask, token_type_ids)
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "reg_chineseBERT_fgm_fold_ensemble.py", line 166, in forward
    a = self.bert(input_ids=ids, attention_mask=mask, token_type_ids=token_type_ids)
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/chinesebert/modeling_chinesebert.py", line 249, in forward
    outputs = self.bert(
  File "/home/zdc/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/chinesebert/modeling_chinesebert.py", line 163, in forward
    embedding_output = self.embeddings(
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/chinesebert/fusion_embedding.py", line 84, in forward
    pinyin_ids.reshape(input_shape[0], seq_length, -1)
AttributeError: 'NoneType' object has no attribute 'reshape'

**Comment by luoshunchong** [comment]
> 在跑chinesebert 时出现这个问题是什么原因呀？ loading data ... The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. The tokenizer class you load from this checkpoint is 'BertTokenizer'. The class this function is called from is 'ChineseBertTokenizerFast'. start training ... --------------------------------- 1 fold --------------------------------- 0%| | 0/3652 [00:00<?, ?it/s] Traceback (most recent call last): File "reg_chineseBERT_fgm_fold_ensemble.py", line 450, in model_train(args, train_df, tokenizer) File "reg_chineseBERT_fgm_fold_ensemble.py", line 315, in model_train outputs = model(ids, mask, token_type_ids) File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "reg_chineseBERT_fgm_fold_ensemble.py", line 166, in forward a = self.bert(input_ids=ids, attention_mask=mask, token_type_ids=token_type_ids) File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/xxx/anaconda3/lib/python3.8/site-packages/chinesebert/modeling_chinesebert.py", line 249, in forward outputs = self.bert( File "/home/zdc/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/xxx/anaconda3/lib/python3.8/site-packages/chinesebert/modeling_chinesebert.py", line 163, in forward embedding_output = self.embeddings( File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/xxx/anaconda3/lib/python3.8/site-packages/chinesebert/fusion_embedding.py", line 84, in forward pinyin_ids.reshape(input_shape[0], seq_length, -1) AttributeError: 'NoneType' object has no attribute 'reshape'

首先，非常抱歉。chineseBERT这份代码所跑出来的结果，我最后并没有用上。可能是我自己没有操作好，导致效果不怎么好。
您出现这个问题是因为，由于ChineseBERT这个模型融合和字形拼音等信息，载入模型与BERT的方式有一点区别。具体的句子Tokenizer和模型载入您可以参考 https://github.com/JunnYu/ChineseBert_pytorch 这个仓库中的代码，写的非常好！
